<Project>
	<PropertyGroup>	
		<RepositoryUrl>https://github.com/OpenSourceKingdom/OSK.Petra.Modules</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>CS1591</NoWarn>
		<Authors>BlankDev117</Authors>
		<LangVersion>12</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>